<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BetterTogetherBetterTog</name>
   <tag></tag>
   <elementGuidId>3edc0e52-7fab-4508-b613-0fbfe131d57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fixture']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'fixture' and @id = 'fixture' and (text() = '
BetterTogether
BetterTogetherEurope
Bristol
Cardiff
Cornwall
Gaia
HealthPump
HealthSolutions
IntentionalHealth
Iotaa
JusticePump
Leeds
MldHealth
MyHealthTag
Sandbox
SharedWell
System
SystemTest
' or . = '
BetterTogether
BetterTogetherEurope
Bristol
Cardiff
Cornwall
Gaia
HealthPump
HealthSolutions
IntentionalHealth
Iotaa
JusticePump
Leeds
MldHealth
MyHealthTag
Sandbox
SharedWell
System
SystemTest
')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fixture</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fixture</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
BetterTogether
BetterTogetherEurope
Bristol
Cardiff
Cornwall
Gaia
HealthPump
HealthSolutions
IntentionalHealth
Iotaa
JusticePump
Leeds
MldHealth
MyHealthTag
Sandbox
SharedWell
System
SystemTest
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixture&quot;)</value>
   </webElementProperties>
</WebElementEntity>
